name: 'Setup'
description: ''

inputs:
  token:
    description: 'GitHub token'
    required: true

  php-version:
    description: 'PHP version'
    required: true

runs:
  using: composite
  steps:
    - uses: myparcelnl/actions/build-docker-image-reg@v4
      id: build
      with:
        registry-password: ${{ inputs.token }}

    - name: 'Handle composer cache'
      uses: actions/cache@v4
      with:
        path: |
          $HOME/.composer
          ./composer.lock
          ./vendor
        key: composer-${{ inputs.php-version }}-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ inputs.php-version }}-${{ hashFiles('**/composer.json') }}-
          composer-${{ hashFiles('**/composer.json') }}-
          composer-

    - name: 'Prepare environment'
      shell: bash
      #language=bash
      run: |
        touch .env
        echo "COMPOSER_HOME=/root/.composer" >> .env
        echo "COMPOSER_MEMORY_LIMIT=-1" >> .env

    - name: 'Install composer dependencies'
      shell: bash
      env:
        IMAGE_NAME: ${{ steps.build.outputs.tagged-image }}
      #language=bash
      run: |
        docker compose run \
          --volume $HOME/.composer:/root/.composer \
          php \
          composer update --no-progress --no-scripts --no-plugins
