name: 'Setup'
description: ''

inputs:
  php-version:
    description: 'PHP version'
    required: true

runs:
  using: composite
  steps:
    - name: 'Handle composer cache'
      uses: actions/cache@v4
      with:
        path: |
          $HOME/.composer
          ./composer.lock
          ./vendor
        key: composer-${{ inputs.php-version }}-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ inputs.php-version }}-${{ hashFiles('**/composer.json') }}-
          composer-${{ hashFiles('**/composer.json') }}-
          composer-

    - uses: myparcelnl/actions/build-docker-image-reg@v4
      with:
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        registry-user: ${{ github.actor }}
        image: 'myparcelnl-pdk:php${{ inputs.php-version }}'

    - name: 'Prepare environment'
      shell: bash
      #language=bash
      run: |
        touch .env.local

    - name: 'Install composer dependencies'
      shell: bash
      #language=bash
      run: |
        docker compose run \
          --volume $HOME/.composer:/root/.composer \
          --env COMPOSER_CACHE_DIR=/root/.composer \
          php \
          composer update --no-progress --no-scripts --no-plugins
