name: 'Setup'
description: ''

inputs:
  php-version:
    description: 'PHP version'
    required: true

runs:
  using: composite
  steps:
    - name: 'Handle composer cache'
      uses: actions/cache@v3
      with:
        path: |
          $HOME/.composer
          ./composer.lock
          ./vendor
        key: composer-${{ inputs.php-version }}-${{ hashFiles('**/composer.json') }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ inputs.php-version }}-${{ hashFiles('**/composer.json') }}-
          composer-${{ hashFiles('**/composer.json') }}-
          composer-

    - uses: myparcelnl/actions/pull-docker-image@v3
      with:
        image: 'ghcr.io/myparcelnl/php-xd:${{ inputs.php-version }}-cli-alpine'

    - name: 'Prepare environment'
      shell: bash
      run: |
        touch .env.local

    - name: 'Install composer dependencies'
      shell: bash
      #language=sh
      run: |
        docker compose run \
          --volume $HOME/.composer:/root/.composer \
          --env COMPOSER_CACHE_DIR=/root/.composer \
          php \
          composer update --no-progress --no-scripts --no-plugins
