version: '3.9'

services:
  php:
    build: .
    command: ['composer', 'install', '--no-interaction', '--no-progress', '--no-suggest']
    init: true
    env_file:
      - .env.local
    volumes:
      - ./:/app

  console:
    build: .
    command: []
    init: true
    entrypoint: ['php', 'bin/console']
    volumes:
      - ./:/app
