version: '3.9'

x-image: &image ghcr.io/myparcelnl/php-xd:7.4-cli-alpine

services:
  php:
    image: *image
    command: [ 'composer', 'install', '--no-interaction', '--no-progress', '--no-suggest' ]
    env_file:
      - .env.local
    volumes:
      - ./:/app

  console:
    image: *image
    command: [ ]
    entrypoint: [ 'php', 'bin/console' ]
    volumes:
      - ./:/app
