x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  # Set in .env
  image: $IMAGE_NAME

services:
  php:
    <<: *common
    init: true
    command: ['composer', 'install', '--no-interaction', '--no-progress']
    env_file:
      - .env
    volumes:
      - ./:/app

  console:
    <<: *common
    init: true
    command: []
    entrypoint: ['php', 'bin/console']
    volumes:
      - ./:/app
