version: '3.9'

services:
  php:
    image: ghcr.io/myparcelnl/php-xd:7.4-cli-alpine
    init: true
    command: [ 'composer', 'install', '--no-interaction', '--no-progress', '--no-suggest' ]
    volumes:
      - ./:/app
