x-common: &common
  init: true
  # Set in .env
  image: $IMAGE_NAME
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/app

services:
  php:
    <<: *common
    command: ['composer', 'install', '--no-interaction', '--no-progress']
    env_file:
      - .env

  console:
    <<: *common
    command: []
    entrypoint: ['php', 'bin/console']
