x-common: &common
  init: true
  image: 'ghcr.io/myparcelnl/pdk:7.4'
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/app

services:
  php:
    <<: *common
    command: ['composer', 'install', '--no-interaction', '--no-progress', '--no-suggest']
    env_file:
      - .env.local

  console:
    <<: *common
    command: []
    entrypoint: ['php', 'bin/console']
