name: 'Upload coverage'
description: 'Upload coverage to Codecov and Codacy.'

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: coverage

    - name: 'Upload coverage to Codecov'
      uses: codecov/codecov-action@v3
      continue-on-error: true

    - name: 'Upload coverage to Codacy'
      uses: codacy/codacy-coverage-reporter-action@v1
      continue-on-error: true
      with:
        api-token: ${{ secrets.CODACY_API_TOKEN }}
