<?php
/** @noinspection StaticClosureCanBeUsedInspection,PhpUnhandledExceptionInspection */

declare(strict_types=1);

use MyParcelNL\Pdk\Base\Factory\PdkFactory;
use MyParcelNL\Pdk\Carrier\Model\CarrierOptions;
use MyParcelNL\Pdk\Plugin\Context;
use MyParcelNL\Pdk\Plugin\Model\PdkOrder;
use MyParcelNL\Pdk\Plugin\Service\ContextService;
use MyParcelNL\Pdk\Shipment\Model\DeliveryOptions;
use MyParcelNL\Pdk\Tests\Bootstrap\MockPdkConfig;
use MyParcelNL\Sdk\src\Support\Arr;

it('gets context data', function (string $id, array $arguments, array $expectation) {
    $pdk = PdkFactory::create(MockPdkConfig::create());

    /** @var \MyParcelNL\Pdk\Plugin\Service\ContextService $service */
    $service = $pdk->get(ContextService::class);

    $context = $service->createContexts([$id], $arguments);

    expect(Arr::dot($context->toArray()))->toEqual($expectation);
})->with([
    'global' => [
        'id'          => Context::ID_GLOBAL,
        'arguments'   => [],
        'expectation' => [
            'global.baseUrl'                                         => 'CMS_URL',
            'global.bootstrapId'                                     => 'myparcel-pdk-bootstrap',
            'global.endpoints.exportAndPrintOrder.body'              => null,
            'global.endpoints.exportAndPrintOrder.headers'           => [],
            'global.endpoints.exportAndPrintOrder.method'            => 'POST',
            'global.endpoints.exportAndPrintOrder.parameters.action' => 'exportAndPrintOrder',
            'global.endpoints.exportAndPrintOrder.path'              => '',
            'global.endpoints.exportOrder.body'                      => null,
            'global.endpoints.exportOrder.headers'                   => [],
            'global.endpoints.exportOrder.method'                    => 'POST',
            'global.endpoints.exportOrder.parameters.action'         => 'exportOrder',
            'global.endpoints.exportOrder.path'                      => '',
            'global.endpoints.getOrderData.body'                     => null,
            'global.endpoints.getOrderData.headers'                  => [],
            'global.endpoints.getOrderData.method'                   => 'GET',
            'global.endpoints.getOrderData.parameters.action'        => 'getOrderData',
            'global.endpoints.getOrderData.path'                     => '',
            'global.event'                                           => 'myparcel_pdk_loaded',
            'global.mode'                                            => 'production',
            'global.pluginSettings'                                  => [],
            'global.translations.apple_tree'                         => 'Appelboom',
            'orderData'                                              => null,
            'deliveryOptionsConfig'                                  => null,
        ],
    ],

    'empty order data' => [
        'id'          => Context::ID_ORDER_DATA,
        'arguments'   => [],
        'expectation' => [
            'global'                => null,
            'orderData'             => [],
            'deliveryOptionsConfig' => null,
        ],
    ],

    'single order' => [
        'id'          => Context::ID_ORDER_DATA,
        'arguments'   => [
            'order' => [
                'externalIdentifier' => '123',
            ],
        ],
        'expectation' => [
            'global'                                                       => null,
            'orderData.0.externalIdentifier'                               => '123',
            'orderData.0.customsDeclaration.contents'                      => 1,
            'orderData.0.customsDeclaration.invoice'                       => null,
            'orderData.0.customsDeclaration.items'                         => [],
            'orderData.0.customsDeclaration.weight'                        => 0,
            'orderData.0.deliveryOptions.carrier'                          => null,
            'orderData.0.deliveryOptions.date'                             => null,
            'orderData.0.deliveryOptions.deliveryType'                     => DeliveryOptions::DEFAULT_DELIVERY_TYPE_NAME,
            'orderData.0.deliveryOptions.labelAmount'                      => 1,
            'orderData.0.deliveryOptions.packageType'                      => DeliveryOptions::DEFAULT_PACKAGE_TYPE_NAME,
            'orderData.0.deliveryOptions.pickupLocation'                   => null,
            'orderData.0.deliveryOptions.shipmentOptions.ageCheck'         => null,
            'orderData.0.deliveryOptions.shipmentOptions.insurance'        => null,
            'orderData.0.deliveryOptions.shipmentOptions.labelDescription' => null,
            'orderData.0.deliveryOptions.shipmentOptions.largeFormat'      => null,
            'orderData.0.deliveryOptions.shipmentOptions.onlyRecipient'    => null,
            'orderData.0.deliveryOptions.shipmentOptions.return'           => null,
            'orderData.0.deliveryOptions.shipmentOptions.sameDayDelivery'  => null,
            'orderData.0.deliveryOptions.shipmentOptions.signature'        => null,
            'orderData.0.label'                                            => null,
            'orderData.0.recipient'                                        => null,
            'orderData.0.sender'                                           => null,
            'orderData.0.shipments'                                        => [],
            'orderData.0.orderLines'                                       => null,
            'orderData.0.orderTotals.orderPrice'                           => 0,
            'orderData.0.orderTotals.orderVat'                             => 0,
            'orderData.0.orderTotals.orderPriceAfterVat'                   => 0,
            'orderData.0.orderTotals.shipmentPrice'                        => null,
            'orderData.0.orderTotals.shipmentVat'                          => null,
            'orderData.0.orderTotals.shipmentPriceAfterVat'                => 0,
            'orderData.0.orderTotals.totalPrice'                           => 0,
            'orderData.0.orderTotals.totalVat'                             => 0,
            'orderData.0.orderTotals.totalPriceAfterVat'                   => 0,
            'orderData.0.shipmentPrice'                                    => null,
            'orderData.0.shipmentVat'                                      => null,
            'deliveryOptionsConfig'                                        => null,
        ],
    ],

    'multiple orders' => [
        'id'          => Context::ID_ORDER_DATA,
        'arguments'   => [
            'order' => [
                [
                    'externalIdentifier' => '123',
                ],
                [
                    'externalIdentifier' => '124',
                ],
            ],
        ],
        'expectation' => [
            'global'                                                       => null,
            'orderData.0.customsDeclaration.contents'                      => 1,
            'orderData.0.customsDeclaration.invoice'                       => null,
            'orderData.0.customsDeclaration.items'                         => [],
            'orderData.0.customsDeclaration.weight'                        => 0,
            'orderData.0.deliveryOptions.carrier'                          => null,
            'orderData.0.deliveryOptions.date'                             => null,
            'orderData.0.deliveryOptions.deliveryType'                     => DeliveryOptions::DEFAULT_DELIVERY_TYPE_NAME,
            'orderData.0.deliveryOptions.labelAmount'                      => 1,
            'orderData.0.deliveryOptions.packageType'                      => DeliveryOptions::DEFAULT_PACKAGE_TYPE_NAME,
            'orderData.0.deliveryOptions.pickupLocation'                   => null,
            'orderData.0.deliveryOptions.shipmentOptions.ageCheck'         => null,
            'orderData.0.deliveryOptions.shipmentOptions.insurance'        => null,
            'orderData.0.deliveryOptions.shipmentOptions.labelDescription' => null,
            'orderData.0.deliveryOptions.shipmentOptions.largeFormat'      => null,
            'orderData.0.deliveryOptions.shipmentOptions.onlyRecipient'    => null,
            'orderData.0.deliveryOptions.shipmentOptions.return'           => null,
            'orderData.0.deliveryOptions.shipmentOptions.sameDayDelivery'  => null,
            'orderData.0.deliveryOptions.shipmentOptions.signature'        => null,
            'orderData.0.externalIdentifier'                               => '123',
            'orderData.0.label'                                            => null,
            'orderData.0.orderLines'                                       => null,
            'orderData.0.orderTotals.orderPrice'                           => 0,
            'orderData.0.orderTotals.orderVat'                             => 0,
            'orderData.0.orderTotals.orderPriceAfterVat'                   => 0,
            'orderData.0.orderTotals.shipmentPrice'                        => null,
            'orderData.0.orderTotals.shipmentVat'                          => null,
            'orderData.0.orderTotals.shipmentPriceAfterVat'                => 0,
            'orderData.0.orderTotals.totalPrice'                           => 0,
            'orderData.0.orderTotals.totalVat'                             => 0,
            'orderData.0.orderTotals.totalPriceAfterVat'                   => 0,
            'orderData.0.shipmentPrice'                                    => null,
            'orderData.0.shipmentVat'                                      => null,
            'orderData.0.recipient'                                        => null,
            'orderData.0.sender'                                           => null,
            'orderData.0.shipments'                                        => [],
            'orderData.1.customsDeclaration.contents'                      => 1,
            'orderData.1.customsDeclaration.invoice'                       => null,
            'orderData.1.customsDeclaration.items'                         => [],
            'orderData.1.customsDeclaration.weight'                        => 0,
            'orderData.1.deliveryOptions.carrier'                          => null,
            'orderData.1.deliveryOptions.date'                             => null,
            'orderData.1.deliveryOptions.deliveryType'                     => DeliveryOptions::DEFAULT_DELIVERY_TYPE_NAME,
            'orderData.1.deliveryOptions.labelAmount'                      => 1,
            'orderData.1.deliveryOptions.packageType'                      => DeliveryOptions::DEFAULT_PACKAGE_TYPE_NAME,
            'orderData.1.deliveryOptions.pickupLocation'                   => null,
            'orderData.1.deliveryOptions.shipmentOptions.ageCheck'         => null,
            'orderData.1.deliveryOptions.shipmentOptions.insurance'        => null,
            'orderData.1.deliveryOptions.shipmentOptions.labelDescription' => null,
            'orderData.1.deliveryOptions.shipmentOptions.largeFormat'      => null,
            'orderData.1.deliveryOptions.shipmentOptions.onlyRecipient'    => null,
            'orderData.1.deliveryOptions.shipmentOptions.return'           => null,
            'orderData.1.deliveryOptions.shipmentOptions.sameDayDelivery'  => null,
            'orderData.1.deliveryOptions.shipmentOptions.signature'        => null,
            'orderData.1.externalIdentifier'                               => '124',
            'orderData.1.label'                                            => null,
            'orderData.1.recipient'                                        => null,
            'orderData.1.sender'                                           => null,
            'orderData.1.shipments'                                        => [],
            'orderData.1.orderLines'                                       => null,
            'orderData.1.orderTotals.orderPrice'                           => 0,
            'orderData.1.orderTotals.orderVat'                             => 0,
            'orderData.1.orderTotals.orderPriceAfterVat'                   => 0,
            'orderData.1.orderTotals.shipmentPrice'                        => null,
            'orderData.1.orderTotals.shipmentVat'                          => null,
            'orderData.1.orderTotals.shipmentPriceAfterVat'                => 0,
            'orderData.1.orderTotals.totalPrice'                           => 0,
            'orderData.1.orderTotals.totalVat'                             => 0,
            'orderData.1.orderTotals.totalPriceAfterVat'                   => 0,
            'orderData.1.shipmentPrice'                                    => null,
            'orderData.1.shipmentVat'                                      => null,
            'deliveryOptionsConfig'                                        => null,
        ],
    ],

    'delivery options config' => [
        'id'          => Context::ID_DELIVERY_OPTIONS_CONFIG,
        'arguments'   => [
            'order' => new PdkOrder(
                [
                    'externalIdentifier' => 'paprika',
                    'shipmentPrice'      => 200,
                    'shipmentVat'        => 42,
                    'deliveryOptions'    => [
                        'carrier'     => CarrierOptions::CARRIER_POSTNL_NAME,
                        'packageType' => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                    ],
                ]
            ),
        ],
        'expectation' => [
            'global'                                                                             => null,
            'orderData'                                                                          => null,
            'deliveryOptionsConfig.strings.addressNotFound'                                      => 'Adresgegevens zijn niet ingevuld',
            'deliveryOptionsConfig.strings.cc'                                                   => null,
            'deliveryOptionsConfig.strings.city'                                                 => null,
            'deliveryOptionsConfig.strings.deliveryTitle'                                        => null,
            'deliveryOptionsConfig.strings.discount'                                             => null,
            'deliveryOptionsConfig.strings.eveningDeliveryTitle'                                 => null,
            'deliveryOptionsConfig.strings.from'                                                 => null,
            'deliveryOptionsConfig.strings.houseNumber'                                          => null,
            'deliveryOptionsConfig.strings.loadMore'                                             => null,
            'deliveryOptionsConfig.strings.morningDeliveryTitle'                                 => null,
            'deliveryOptionsConfig.strings.onlyRecipientTitle'                                   => null,
            'deliveryOptionsConfig.strings.openingHours'                                         => null,
            'deliveryOptionsConfig.strings.pickupLocationsListButton'                            => null,
            'deliveryOptionsConfig.strings.pickupLocationsMapButton'                             => null,
            'deliveryOptionsConfig.strings.pickupTitle'                                          => null,
            'deliveryOptionsConfig.strings.postcode'                                             => null,
            'deliveryOptionsConfig.strings.recipientTitle'                                       => null,
            'deliveryOptionsConfig.strings.retry'                                                => null,
            'deliveryOptionsConfig.strings.saturdayDeliveryTitle'                                => null,
            'deliveryOptionsConfig.strings.signatureTitle'                                       => null,
            'deliveryOptionsConfig.strings.standardDeliveryTitle'                                => null,
            'deliveryOptionsConfig.strings.wrongNumberPostalCode'                                => null,
            'deliveryOptionsConfig.strings.wrongPostalCodeCity'                                  => null,
            'deliveryOptionsConfig.config.apiBaseUrl'                                            => 'api.myparcel.nl',
            'deliveryOptionsConfig.config.currency'                                              => 'EUR',
            'deliveryOptionsConfig.config.packageType'                                           => 'package',
            'deliveryOptionsConfig.config.locale'                                                => 'nl-NL',
            'deliveryOptionsConfig.config.platform'                                              => 'myparcel',
            'deliveryOptionsConfig.config.basePrice'                                             => 242,
            'deliveryOptionsConfig.config.showPriceSurcharge'                                    => true,
            'deliveryOptionsConfig.config.pickupLocationsDefaultView'                            => 'map',
            'deliveryOptionsConfig.config.priceStandardDelivery'                                 => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowDeliveryOptions'           => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowEveningDelivery'           => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowMondayDelivery'            => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowMorningDelivery'           => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowOnlyRecipient'             => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowPickupLocations'           => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowSameDayDelivery'           => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowSaturdayDelivery'          => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowSignature'                 => true,
            'deliveryOptionsConfig.config.carrierSettings.postnl.defaultPackageType'             => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.digitalStampDefaultWeight'      => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportAgeCheck'                 => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportExtraLargeFormat'         => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportInsured'                  => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportInsuredAmount'            => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportInsuredAmountMax'         => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportInsuredForBe'             => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportOnlyRecipient'            => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportReturnShipments'          => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.exportSignature'                => false,
            'deliveryOptionsConfig.config.carrierSettings.postnl.priceEveningDelivery'           => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.priceMorningDelivery'           => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.priceOnlyRecipient'             => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.pricePackageTypeDigitalStamp'   => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.pricePackageTypeMailbox'        => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.pricePickup'                    => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.priceSameDayDelivery'           => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.priceSignature'                 => 80,
            'deliveryOptionsConfig.config.carrierSettings.postnl.priceStandardDelivery'          => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.allowShowDeliveryDate'          => null,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDays.0'                  => 1,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDays.1'                  => 2,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDays.2'                  => 3,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDays.3'                  => 4,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDays.4'                  => 5,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDays.5'                  => 6,
            'deliveryOptionsConfig.config.carrierSettings.postnl.cutoffTime'                     => '17:00',
            'deliveryOptionsConfig.config.carrierSettings.postnl.cutoffTimeSameDay'              => '10:00',
            'deliveryOptionsConfig.config.carrierSettings.postnl.saturdayCutoffTime'             => '15:30',
            'deliveryOptionsConfig.config.carrierSettings.postnl.deliveryDaysWindow'             => 7,
            'deliveryOptionsConfig.config.carrierSettings.postnl.dropOffDelay'                   => 1,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowDeliveryOptions'         => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowEveningDelivery'         => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowMondayDelivery'          => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowMorningDelivery'         => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowOnlyRecipient'           => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowPickupLocations'         => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowSameDayDelivery'         => true,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowSaturdayDelivery'        => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowSignature'               => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.defaultPackageType'           => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.digitalStampDefaultWeight'    => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportAgeCheck'               => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportExtraLargeFormat'       => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportInsured'                => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportInsuredAmount'          => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportInsuredAmountMax'       => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportInsuredForBe'           => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportOnlyRecipient'          => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportReturnShipments'        => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.exportSignature'              => false,
            'deliveryOptionsConfig.config.carrierSettings.instabox.priceEveningDelivery'         => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.priceMorningDelivery'         => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.priceOnlyRecipient'           => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.pricePackageTypeDigitalStamp' => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.pricePackageTypeMailbox'      => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.pricePickup'                  => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.priceSameDayDelivery'         => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.priceSignature'               => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.priceStandardDelivery'        => null,
            'deliveryOptionsConfig.config.carrierSettings.instabox.allowShowDeliveryDate'        => null,
        ],
    ],
]);

it('handles invalid context keys', function () {
    $pdk = PdkFactory::create(MockPdkConfig::create());

    /** @var \MyParcelNL\Pdk\Plugin\Service\ContextService $service */
    $service    = $pdk->get(ContextService::class);
    $contextBag = $service->createContexts(['random_word']);

    expect($contextBag->toArray())->toEqual([
        'global'                => null,
        'orderData'             => null,
        'deliveryOptionsConfig' => null,
    ]);
});
