<?php
/** @noinspection PhpUnhandledExceptionInspection,StaticClosureCanBeUsedInspection */

declare(strict_types=1);

namespace MyParcelNL\Pdk\Storage;

use MyParcelNL\Pdk\Base\Factory\PdkFactory;
use MyParcelNL\Pdk\Carrier\Model\CarrierOptions;
use MyParcelNL\Pdk\Plugin\Model\PdkOrder;
use MyParcelNL\Pdk\Shipment\Model\DeliveryOptions;
use MyParcelNL\Pdk\Tests\Bootstrap\MockPdkConfig;
use MyParcelNL\Pdk\Validation\Validator;
use MyParcelNL\Sdk\src\Support\Arr;

beforeEach(function () {
    PdkFactory::create(MockPdkConfig::create());
});

it('returns available options from validator', function ($input, $output) {
    $pdkOrder  = new PdkOrder($input);
    $validator = new Validator($pdkOrder);

    expect(Arr::dot($validator->getValidationRules()))
        ->toBe($output);
})->with([
    'order with one attribute'  => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => null,
                'date'            => '2022-02-02',
                'deliveryType'    => null,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 100,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => [
            'carrier'                                                   => 'postnl',
            'packageType.id'                                            => 1,
            'packageType.name'                                          => 'package',
            'packageType.options.insurance.type'                        => 'integer',
            'packageType.options.insurance.enum.0'                      => 0,
            'packageType.options.insurance.enum.1'                      => 100,
            'packageType.options.insurance.enum.2'                      => 250,
            'packageType.options.insurance.enum.3'                      => 500,
            'packageType.options.insurance.enum.4'                      => 1000,
            'packageType.options.insurance.enum.5'                      => 1500,
            'packageType.options.insurance.enum.6'                      => 2000,
            'packageType.options.insurance.enum.7'                      => 2500,
            'packageType.options.insurance.enum.8'                      => 3000,
            'packageType.options.insurance.enum.9'                      => 3500,
            'packageType.options.insurance.enum.10'                     => 4000,
            'packageType.options.insurance.enum.11'                     => 4500,
            'packageType.options.insurance.enum.12'                     => 5000,
            'packageType.options.ageCheck.type'                         => 'boolean',
            'packageType.options.ageCheck.enum.0'                       => false,
            'packageType.options.ageCheck.enum.1'                       => true,
            'packageType.options.signature.type'                        => 'boolean',
            'packageType.options.signature.enum.0'                      => false,
            'packageType.options.signature.enum.1'                      => true,
            'packageType.options.onlyRecipient.type'                    => 'boolean',
            'packageType.options.onlyRecipient.enum.0'                  => false,
            'packageType.options.onlyRecipient.enum.1'                  => true,
            'packageType.options.return.type'                           => 'boolean',
            'packageType.options.return.enum.0'                         => false,
            'packageType.options.return.enum.1'                         => true,
            'packageType.options.largeFormat.type'                      => 'boolean',
            'packageType.options.largeFormat.enum.0'                    => false,
            'packageType.options.largeFormat.enum.1'                    => true,
            'packageType.requirements.weight.minimum'                   => 0,
            'packageType.requirements.weight.maximum'                   => 23000,
            'packageType.requirements.ageCheck.enum.0'                  => true,
            'packageType.requirements.ageCheck.options.signature.0'     => true,
            'packageType.requirements.ageCheck.options.onlyRecipient.0' => true,
            'packageType.requirements.largeFormat.enum.0'               => true,
            'packageType.requirements.largeFormat.property'             => 'weight',
            'packageType.requirements.largeFormat.minimum'              => 0,
            'packageType.requirements.largeFormat.maximum'              => 30000,
            'deliveryType'                                              => [],
            'options.insurance.type'                                    => 'integer',
            'options.insurance.enum.0'                                  => 0,
            'options.insurance.enum.1'                                  => 100,
            'options.insurance.enum.2'                                  => 250,
            'options.insurance.enum.3'                                  => 500,
            'options.insurance.enum.4'                                  => 1000,
            'options.insurance.enum.5'                                  => 1500,
            'options.insurance.enum.6'                                  => 2000,
            'options.insurance.enum.7'                                  => 2500,
            'options.insurance.enum.8'                                  => 3000,
            'options.insurance.enum.9'                                  => 3500,
            'options.insurance.enum.10'                                 => 4000,
            'options.insurance.enum.11'                                 => 4500,
            'options.insurance.enum.12'                                 => 5000,
            'options.ageCheck.type'                                     => 'boolean',
            'options.ageCheck.enum.0'                                   => false,
            'options.ageCheck.enum.1'                                   => true,
            'options.signature.type'                                    => 'boolean',
            'options.signature.enum.0'                                  => false,
            'options.signature.enum.1'                                  => true,
            'options.onlyRecipient.type'                                => 'boolean',
            'options.onlyRecipient.enum.0'                              => false,
            'options.onlyRecipient.enum.1'                              => true,
            'options.return.type'                                       => 'boolean',
            'options.return.enum.0'                                     => false,
            'options.return.enum.1'                                     => true,
            'options.largeFormat.type'                                  => 'boolean',
            'options.largeFormat.enum.0'                                => false,
            'options.largeFormat.enum.1'                                => true,
            'requirements.weight.minimum'                               => 0,
            'requirements.weight.maximum'                               => 23000,
            'requirements.ageCheck.enum.0'                              => true,
            'requirements.ageCheck.options.signature.0'                 => true,
            'requirements.ageCheck.options.onlyRecipient.0'             => true,
            'requirements.largeFormat.enum.0'                           => true,
            'requirements.largeFormat.property'                         => 'weight',
            'requirements.largeFormat.minimum'                          => 0,
            'requirements.largeFormat.maximum'                          => 30000,
        ],
    ],
    'order with two attributes' => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => 'postnl',
                'date'            => '2022-02-02',
                'deliveryType'    => 'standard',
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 100,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => [
            'carrier'                                                   => 'postnl',
            'packageType.id'                                            => 1,
            'packageType.name'                                          => 'package',
            'packageType.options.insurance.type'                        => 'integer',
            'packageType.options.insurance.enum.0'                      => 0,
            'packageType.options.insurance.enum.1'                      => 100,
            'packageType.options.insurance.enum.2'                      => 250,
            'packageType.options.insurance.enum.3'                      => 500,
            'packageType.options.insurance.enum.4'                      => 1000,
            'packageType.options.insurance.enum.5'                      => 1500,
            'packageType.options.insurance.enum.6'                      => 2000,
            'packageType.options.insurance.enum.7'                      => 2500,
            'packageType.options.insurance.enum.8'                      => 3000,
            'packageType.options.insurance.enum.9'                      => 3500,
            'packageType.options.insurance.enum.10'                     => 4000,
            'packageType.options.insurance.enum.11'                     => 4500,
            'packageType.options.insurance.enum.12'                     => 5000,
            'packageType.options.ageCheck.type'                         => 'boolean',
            'packageType.options.ageCheck.enum.0'                       => false,
            'packageType.options.ageCheck.enum.1'                       => true,
            'packageType.options.signature.type'                        => 'boolean',
            'packageType.options.signature.enum.0'                      => false,
            'packageType.options.signature.enum.1'                      => true,
            'packageType.options.onlyRecipient.type'                    => 'boolean',
            'packageType.options.onlyRecipient.enum.0'                  => false,
            'packageType.options.onlyRecipient.enum.1'                  => true,
            'packageType.options.return.type'                           => 'boolean',
            'packageType.options.return.enum.0'                         => false,
            'packageType.options.return.enum.1'                         => true,
            'packageType.options.largeFormat.type'                      => 'boolean',
            'packageType.options.largeFormat.enum.0'                    => false,
            'packageType.options.largeFormat.enum.1'                    => true,
            'packageType.requirements.weight.minimum'                   => 0,
            'packageType.requirements.weight.maximum'                   => 23000,
            'packageType.requirements.ageCheck.enum.0'                  => true,
            'packageType.requirements.ageCheck.options.signature.0'     => true,
            'packageType.requirements.ageCheck.options.onlyRecipient.0' => true,
            'packageType.requirements.largeFormat.enum.0'               => true,
            'packageType.requirements.largeFormat.property'             => 'weight',
            'packageType.requirements.largeFormat.minimum'              => 0,
            'packageType.requirements.largeFormat.maximum'              => 30000,
            'deliveryType.id'                                           => 2,
            'deliveryType.name'                                         => 'standard',
            'options.insurance.type'                                    => 'integer',
            'options.insurance.enum.0'                                  => 0,
            'options.insurance.enum.1'                                  => 100,
            'options.insurance.enum.2'                                  => 250,
            'options.insurance.enum.3'                                  => 500,
            'options.insurance.enum.4'                                  => 1000,
            'options.insurance.enum.5'                                  => 1500,
            'options.insurance.enum.6'                                  => 2000,
            'options.insurance.enum.7'                                  => 2500,
            'options.insurance.enum.8'                                  => 3000,
            'options.insurance.enum.9'                                  => 3500,
            'options.insurance.enum.10'                                 => 4000,
            'options.insurance.enum.11'                                 => 4500,
            'options.insurance.enum.12'                                 => 5000,
            'options.ageCheck.type'                                     => 'boolean',
            'options.ageCheck.enum.0'                                   => false,
            'options.ageCheck.enum.1'                                   => true,
            'options.signature.type'                                    => 'boolean',
            'options.signature.enum.0'                                  => false,
            'options.signature.enum.1'                                  => true,
            'options.onlyRecipient.type'                                => 'boolean',
            'options.onlyRecipient.enum.0'                              => false,
            'options.onlyRecipient.enum.1'                              => true,
            'options.return.type'                                       => 'boolean',
            'options.return.enum.0'                                     => false,
            'options.return.enum.1'                                     => true,
            'options.largeFormat.type'                                  => 'boolean',
            'options.largeFormat.enum.0'                                => false,
            'options.largeFormat.enum.1'                                => true,
            'requirements.weight.minimum'                               => 0,
            'requirements.weight.maximum'                               => 23000,
            'requirements.ageCheck.enum.0'                              => true,
            'requirements.ageCheck.options.signature.0'                 => true,
            'requirements.ageCheck.options.onlyRecipient.0'             => true,
            'requirements.largeFormat.enum.0'                           => true,
            'requirements.largeFormat.property'                         => 'weight',
            'requirements.largeFormat.minimum'                          => 0,
            'requirements.largeFormat.maximum'                          => 30000,
        ],
    ],
    'row order'                 => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'US',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => null,
                'date'            => '2022-02-02',
                'deliveryType'    => null,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 100,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => [
            'carrier'                                 => 'postnl',
            'packageType.id'                          => 1,
            'packageType.name'                        => 'package',
            'packageType.options.insurance.type'      => 'integer',
            'packageType.options.insurance.enum.0'    => 200,
            'packageType.requirements.weight.minimum' => 1,
            'packageType.requirements.weight.maximum' => 20000,
            'deliveryType'                            => [],
            'options.insurance.type'                  => 'integer',
            'options.insurance.enum.0'                => 200,
            'requirements.weight.minimum'             => 1,
            'requirements.weight.maximum'             => 20000,
        ],
    ],
    'only morning delivery'     => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => null,
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => null,
                'date'            => '2022-02-02',
                'deliveryType'    => DeliveryOptions::DELIVERY_TYPE_MORNING_NAME,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 100,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => [
            'carrier'                                                   => 'postnl',
            'packageType.id'                                            => 1,
            'packageType.name'                                          => 'package',
            'packageType.options.insurance.type'                        => 'integer',
            'packageType.options.insurance.enum.0'                      => 0,
            'packageType.options.insurance.enum.1'                      => 100,
            'packageType.options.insurance.enum.2'                      => 250,
            'packageType.options.insurance.enum.3'                      => 500,
            'packageType.options.insurance.enum.4'                      => 1000,
            'packageType.options.insurance.enum.5'                      => 1500,
            'packageType.options.insurance.enum.6'                      => 2000,
            'packageType.options.insurance.enum.7'                      => 2500,
            'packageType.options.insurance.enum.8'                      => 3000,
            'packageType.options.insurance.enum.9'                      => 3500,
            'packageType.options.insurance.enum.10'                     => 4000,
            'packageType.options.insurance.enum.11'                     => 4500,
            'packageType.options.insurance.enum.12'                     => 5000,
            'packageType.options.ageCheck.type'                         => 'boolean',
            'packageType.options.ageCheck.enum.0'                       => false,
            'packageType.options.ageCheck.enum.1'                       => true,
            'packageType.options.signature.type'                        => 'boolean',
            'packageType.options.signature.enum.0'                      => false,
            'packageType.options.signature.enum.1'                      => true,
            'packageType.options.onlyRecipient.type'                    => 'boolean',
            'packageType.options.onlyRecipient.enum.0'                  => false,
            'packageType.options.onlyRecipient.enum.1'                  => true,
            'packageType.options.return.type'                           => 'boolean',
            'packageType.options.return.enum.0'                         => false,
            'packageType.options.return.enum.1'                         => true,
            'packageType.options.largeFormat.type'                      => 'boolean',
            'packageType.options.largeFormat.enum.0'                    => false,
            'packageType.options.largeFormat.enum.1'                    => true,
            'packageType.requirements.weight.minimum'                   => 0,
            'packageType.requirements.weight.maximum'                   => 23000,
            'packageType.requirements.ageCheck.enum.0'                  => true,
            'packageType.requirements.ageCheck.options.signature.0'     => true,
            'packageType.requirements.ageCheck.options.onlyRecipient.0' => true,
            'packageType.requirements.largeFormat.enum.0'               => true,
            'packageType.requirements.largeFormat.property'             => 'weight',
            'packageType.requirements.largeFormat.minimum'              => 0,
            'packageType.requirements.largeFormat.maximum'              => 30000,
            'deliveryType.id'                                           => 1,
            'deliveryType.name'                                         => 'morning',
            'deliveryType.options.ageCheck.type'                        => 'boolean',
            'deliveryType.options.ageCheck.enum.0'                      => false,
            'deliveryType.options.onlyRecipient.type'                   => 'boolean',
            'deliveryType.options.onlyRecipient.enum.0'                 => true,
            'options.insurance.type'                                    => 'integer',
            'options.insurance.enum.0'                                  => 0,
            'options.insurance.enum.1'                                  => 100,
            'options.insurance.enum.2'                                  => 250,
            'options.insurance.enum.3'                                  => 500,
            'options.insurance.enum.4'                                  => 1000,
            'options.insurance.enum.5'                                  => 1500,
            'options.insurance.enum.6'                                  => 2000,
            'options.insurance.enum.7'                                  => 2500,
            'options.insurance.enum.8'                                  => 3000,
            'options.insurance.enum.9'                                  => 3500,
            'options.insurance.enum.10'                                 => 4000,
            'options.insurance.enum.11'                                 => 4500,
            'options.insurance.enum.12'                                 => 5000,
            'options.ageCheck.type'                                     => 'boolean',
            'options.ageCheck.enum.0'                                   => false,
            'options.signature.type'                                    => 'boolean',
            'options.signature.enum.0'                                  => false,
            'options.signature.enum.1'                                  => true,
            'options.onlyRecipient.type'                                => 'boolean',
            'options.onlyRecipient.enum.0'                              => true,
            'options.return.type'                                       => 'boolean',
            'options.return.enum.0'                                     => false,
            'options.return.enum.1'                                     => true,
            'options.largeFormat.type'                                  => 'boolean',
            'options.largeFormat.enum.0'                                => false,
            'options.largeFormat.enum.1'                                => true,
            'requirements.weight.minimum'                               => 0,
            'requirements.weight.maximum'                               => 23000,
            'requirements.ageCheck.enum.0'                              => true,
            'requirements.ageCheck.options.signature.0'                 => true,
            'requirements.ageCheck.options.onlyRecipient.0'             => true,
            'requirements.largeFormat.enum.0'                           => true,
            'requirements.largeFormat.property'                         => 'weight',
            'requirements.largeFormat.minimum'                          => 0,
            'requirements.largeFormat.maximum'                          => 30000,
        ],
    ],
]);

it('returns true/false from validator', function ($input, $output) {
    $pdkOrder  = new PdkOrder($input);
    $validator = (new Validator($pdkOrder))->validate();

    expect($validator)
        ->toBe($output);
})->with([
    'postnl order with same day delivery'        => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => 'postnl',
                'date'            => '2022-02-02',
                'deliveryType'    => 'standard',
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 100,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => true,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
    'morning delivery with age check'            => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => 'postnl',
                'date'            => '2022-02-02',
                'deliveryType'    => DeliveryOptions::DELIVERY_TYPE_MORNING_NAME,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
    'correct instabox order'                     => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => 'instabox',
                'date'            => '2022-02-02',
                'deliveryType'    => DeliveryOptions::DELIVERY_TYPE_STANDARD_NAME,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => false,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => true,
                    'signature'        => true,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => false,
    ],
    'EU package without insurance'               => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'FR',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => 'postnl',
                'date'            => '2022-02-02',
                'deliveryType'    => null,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => true,
                    'signature'        => true,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
    'correct BE mailbox package'                 => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'BE',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'BE',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => 'postnl',
                'date'            => '2022-02-02',
                'deliveryType'    => null,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => true,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
    'pickup without location code'               => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'BE',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => CarrierOptions::CARRIER_POSTNL_NAME,
                'date'            => '2022-02-02',
                'deliveryType'    => DeliveryOptions::DELIVERY_TYPE_PICKUP_NAME,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 10000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
    'order with too much weight'                 => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'BE',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => CarrierOptions::CARRIER_POSTNL_NAME,
                'date'            => '2022-02-02',
                'deliveryType'    => DeliveryOptions::DELIVERY_TYPE_PICKUP_NAME,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 31000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
    'order with age check and without signature' => [
        'input'  => [
            'externalIdentifier' => '1',
            'recipient'          => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'sender'             => [
                'cc'         => 'NL',
                'city'       => 'Hoofddorp',
                'postalCode' => '2132JE',
                'street'     => 'Antareslaan 31',
                'number'     => '31',
                'person'     => 'Mike Parcel',
                'email'      => 'test@myparcel.nl',
                'phone'      => '0619438574',
            ],
            'deliveryOptions'    => [
                'carrier'         => CarrierOptions::CARRIER_POSTNL_NAME,
                'date'            => '2022-02-02',
                'deliveryType'    => DeliveryOptions::DELIVERY_TYPE_STANDARD_NAME,
                'packageType'     => DeliveryOptions::PACKAGE_TYPE_PACKAGE_NAME,
                'pickupLocation'  => null,
                'shipmentOptions' => [
                    'ageCheck'         => true,
                    'insurance'        => 0,
                    'labelDescription' => 'Pizzadoos',
                    'largeFormat'      => false,
                    'onlyRecipient'    => false,
                    'return'           => false,
                    'sameDayDelivery'  => false,
                    'signature'        => false,
                ],
            ],
            'physicalProperties' => [
                'weight' => 31000,
            ],
            'shipments'          => null,
        ],
        'output' => true,
    ],
]);
