<?php
/** @noinspection StaticClosureCanBeUsedInspection,PhpUnhandledExceptionInspection */

declare(strict_types=1);

use MyParcelNL\Pdk\Api\Service\ApiServiceInterface;
use MyParcelNL\Pdk\Base\Factory\PdkFactory;
use MyParcelNL\Pdk\Carrier\Model\CarrierOptions;
use MyParcelNL\Pdk\Shipment\Repository\ShipmentRepository;
use MyParcelNL\Pdk\Tests\Api\Response\ExampleGetShipmentsFromContractResponse;
use MyParcelNL\Pdk\Tests\Api\Response\ExampleGetShipmentsResponse;
use MyParcelNL\Pdk\Tests\Api\Response\ExampleGetShipmentsResponseWithDropOffPoint;
use MyParcelNL\Pdk\Tests\Api\Response\ExampleGetShipmentsResponseWithPickup;
use MyParcelNL\Pdk\Tests\Bootstrap\MockPdkConfig;
use MyParcelNL\Sdk\src\Support\Arr;

/**
 * @covers \MyParcelNL\Pdk\Shipment\Repository\ShipmentRepository::query
 */

it('creates shipment collection from queried data', function (string $responseClass, array $output) {
    $pdk = PdkFactory::create(MockPdkConfig::create());

    /** @var \MyParcelNL\Pdk\Tests\Bootstrap\MockApiService $api */
    $api = $pdk->get(ApiServiceInterface::class);
    $api->getMock()
        ->append(new $responseClass());

    /** @var \MyParcelNL\Pdk\Shipment\Repository\ShipmentRepository $repository */
    $repository = $pdk->get(ShipmentRepository::class);

    $response = $repository->query([]);
    $shipment = $response->first();
    $array    = $shipment->toArray();

    // No need to test this data here.
    $arrayWithoutCapabilities = Arr::except($array, ['carrier.capabilities', 'carrier.returnCapabilities']);

    expect($response)
        ->and($shipment->carrier->name)
        ->toBe($shipment->deliveryOptions->carrier)
        ->and(Arr::dot($arrayWithoutCapabilities))
        ->toEqual($output);
})->with([
    'normal shipment'              => [
        'response' => ExampleGetShipmentsResponse::class,
        'output'   => [
            'apiKey'                                           => null,
            'barcode'                                          => 'CV515676839NL',
            'carrier.human'                                    => null,
            'carrier.id'                                       => CarrierOptions::CARRIER_POSTNL_ID,
            'carrier.isDefault'                                => null,
            'carrier.label'                                    => null,
            'carrier.name'                                     => CarrierOptions::CARRIER_POSTNL_NAME,
            'carrier.optional'                                 => null,
            'carrier.primary'                                  => true,
            'carrier.subscriptionId'                           => null,
            'carrier.type'                                     => 'main',
            'collectionContact'                                => null,
            'created'                                          => '2021-04-26 14:06:45',
            'createdBy'                                        => 35159,
            'customsDeclaration.contents'                      => 1,
            'customsDeclaration.invoice'                       => '123456',
            'customsDeclaration.items.0.amount'                => 1,
            'customsDeclaration.items.0.classification'        => '123456',
            'customsDeclaration.items.0.country'               => 'NL',
            'customsDeclaration.items.0.description'           => 'Product',
            'customsDeclaration.items.0.itemValue.amount'      => 1000,
            'customsDeclaration.items.0.itemValue.currency'    => 'EUR',
            'customsDeclaration.items.0.weight'                => 500,
            'customsDeclaration.weight'                        => 3500,
            'delayed'                                          => false,
            'delivered'                                        => false,
            'deliveryOptions.carrier'                          => CarrierOptions::CARRIER_POSTNL_NAME,
            'deliveryOptions.date'                             => null,
            'deliveryOptions.deliveryType'                     => '2',
            'deliveryOptions.labelAmount'                      => 1,
            'deliveryOptions.packageType'                      => '1',
            'deliveryOptions.pickupLocation'                   => null,
            'deliveryOptions.shipmentOptions.ageCheck'         => false,
            'deliveryOptions.shipmentOptions.insurance'        => 20000,
            'deliveryOptions.shipmentOptions.labelDescription' => 'standaard kenmerk',
            'deliveryOptions.shipmentOptions.largeFormat'      => false,
            'deliveryOptions.shipmentOptions.onlyRecipient'    => false,
            'deliveryOptions.shipmentOptions.return'           => false,
            'deliveryOptions.shipmentOptions.sameDayDelivery'  => null,
            'deliveryOptions.shipmentOptions.signature'        => false,
            'dropOffPoint'                                     => null,
            'externalIdentifier'                               => 'CV515676839NL',
            'id'                                               => 7,
            'isReturn'                                         => false,
            'linkConsumerPortal'                               => null,
            'modified'                                         => '2021-05-03 07:42:43',
            'modifiedBy'                                       => 35159,
            'multiCollo'                                       => false,
            'multiColloMainShipmentId'                         => null,
            'orderId'                                          => null,
            'partnerTrackTraces'                               => [],
            'physicalProperties.height'                        => 20,
            'physicalProperties.length'                        => 40,
            'physicalProperties.weight'                        => 3500,
            'physicalProperties.width'                         => 30,
            'recipient.boxNumber'                              => null,
            'recipient.cc'                                     => 'CW',
            'recipient.city'                                   => 'Willemstad',
            'recipient.company'                                => 'MyParcel',
            'recipient.email'                                  => 'meneer@groenteboer.nl',
            'recipient.fullStreet'                             => null,
            'recipient.number'                                 => '12',
            'recipient.numberSuffix'                           => null,
            'recipient.person'                                 => 'Joep Meloen',
            'recipient.phone'                                  => '+31699335577',
            'recipient.postalCode'                             => null,
            'recipient.region'                                 => null,
            'recipient.state'                                  => null,
            'recipient.street'                                 => 'Schottegatweg Oost',
            'recipient.streetAdditionalInfo'                   => null,
            'referenceIdentifier'                              => 'GeheimeDingen-1',
            'sender.boxNumber'                                 => null,
            'sender.cc'                                        => 'NL',
            'sender.city'                                      => 'Hoofddorp',
            'sender.company'                                   => 'Geheime Dingen',
            'sender.email'                                     => 'shop@geheimedingen.nl',
            'sender.fullStreet'                                => null,
            'sender.number'                                    => '31',
            'sender.numberSuffix'                              => null,
            'sender.person'                                    => 'Denzel Crocker',
            'sender.phone'                                     => '0612345678',
            'sender.postalCode'                                => '2132 JE',
            'sender.region'                                    => null,
            'sender.state'                                     => null,
            'sender.street'                                    => 'Antareslaan',
            'sender.streetAdditionalInfo'                      => null,
            'shopId'                                           => 6,
            'status'                                           => 2,
            'updated'                                          => null,
        ],
    ],
    'shipment with drop-off point' => [
        'response' => ExampleGetShipmentsResponseWithDropOffPoint::class,
        'output'   => [
            'apiKey'                                           => null,
            'barcode'                                          => '',
            'carrier.human'                                    => null,
            'carrier.id'                                       => CarrierOptions::CARRIER_INSTABOX_ID,
            'carrier.isDefault'                                => null,
            'carrier.label'                                    => null,
            'carrier.name'                                     => CarrierOptions::CARRIER_INSTABOX_NAME,
            'carrier.optional'                                 => null,
            'carrier.primary'                                  => true,
            'carrier.subscriptionId'                           => null,
            'carrier.type'                                     => 'main',
            'collectionContact'                                => null,
            'created'                                          => '2022-07-13 11:56:18',
            'createdBy'                                        => 82444,
            'customsDeclaration'                               => null,
            'delayed'                                          => false,
            'delivered'                                        => false,
            'deliveryOptions.carrier'                          => 'instabox',
            'deliveryOptions.date'                             => null,
            'deliveryOptions.deliveryType'                     => '2',
            'deliveryOptions.labelAmount'                      => 1,
            'deliveryOptions.packageType'                      => '1',
            'deliveryOptions.pickupLocation'                   => null,
            'deliveryOptions.shipmentOptions.ageCheck'         => true,
            'deliveryOptions.shipmentOptions.insurance'        => 0,
            'deliveryOptions.shipmentOptions.labelDescription' => 'Vliegtuig',
            'deliveryOptions.shipmentOptions.largeFormat'      => true,
            'deliveryOptions.shipmentOptions.onlyRecipient'    => true,
            'deliveryOptions.shipmentOptions.return'           => true,
            'deliveryOptions.shipmentOptions.sameDayDelivery'  => true,
            'deliveryOptions.shipmentOptions.signature'        => false,
            'dropOffPoint.boxNumber'                           => null,
            'dropOffPoint.cc'                                  => 'NL',
            'dropOffPoint.city'                                => 'Leiden',
            'dropOffPoint.fullStreet'                          => null,
            'dropOffPoint.locationCode'                        => 'ed14eb91-7374-4dcc-a41d-34c0d3e45c01',
            'dropOffPoint.locationName'                        => 'Instabox',
            'dropOffPoint.number'                              => '2',
            'dropOffPoint.numberSuffix'                        => 'H',
            'dropOffPoint.postalCode'                          => '2321 TD',
            'dropOffPoint.region'                              => null,
            'dropOffPoint.retailNetworkId'                     => null,
            'dropOffPoint.state'                               => null,
            'dropOffPoint.street'                              => 'Telderskade',
            'dropOffPoint.streetAdditionalInfo'                => null,
            'externalIdentifier'                               => null,
            'id'                                               => 136510070,
            'isReturn'                                         => false,
            'linkConsumerPortal'                               => null,
            'modified'                                         => '2022-07-13 11:56:18',
            'modifiedBy'                                       => 82444,
            'multiCollo'                                       => false,
            'multiColloMainShipmentId'                         => null,
            'orderId'                                          => null,
            'partnerTrackTraces'                               => [],
            'physicalProperties.height'                        => null,
            'physicalProperties.length'                        => null,
            'physicalProperties.weight'                        => 5000,
            'physicalProperties.width'                         => null,
            'recipient.boxNumber'                              => null,
            'recipient.cc'                                     => 'NL',
            'recipient.city'                                   => 'Wenum Wiesel',
            'recipient.company'                                => null,
            'recipient.email'                                  => 'test@webshopje.nl',
            'recipient.fullStreet'                             => null,
            'recipient.number'                                 => '12',
            'recipient.numberSuffix'                           => 'c',
            'recipient.person'                                 => 'Epke Zonderland',
            'recipient.phone'                                  => '0172765435',
            'recipient.postalCode'                             => '7345AB',
            'recipient.region'                                 => null,
            'recipient.state'                                  => null,
            'recipient.street'                                 => 'Wieselsedwarsweg',
            'recipient.streetAdditionalInfo'                   => null,
            'referenceIdentifier'                              => '',
            'sender.boxNumber'                                 => null,
            'sender.cc'                                        => 'NL',
            'sender.city'                                      => 'Hoofddorp',
            'sender.company'                                   => 'MyParcel',
            'sender.email'                                     => 'mrparcel@myparcel.nl',
            'sender.fullStreet'                                => null,
            'sender.number'                                    => '31',
            'sender.numberSuffix'                              => null,
            'sender.person'                                    => 'Mister Parcel',
            'sender.phone'                                     => '0606607834',
            'sender.postalCode'                                => '2132JE',
            'sender.region'                                    => null,
            'sender.state'                                     => null,
            'sender.street'                                    => 'Antareslaan',
            'sender.streetAdditionalInfo'                      => null,
            'shopId'                                           => 93683,
            'status'                                           => 1,
            'updated'                                          => null,
        ],
    ],
    'shipment with pickup'         => [
        'response' => ExampleGetShipmentsResponseWithPickup::class,
        'output'   => [
            'apiKey'                                              => null,
            'barcode'                                             => '3SMYPA056396924',
            'carrier.human'                                       => null,
            'carrier.id'                                          => CarrierOptions::CARRIER_POSTNL_ID,
            'carrier.isDefault'                                   => null,
            'carrier.label'                                       => null,
            'carrier.name'                                        => CarrierOptions::CARRIER_POSTNL_NAME,
            'carrier.optional'                                    => null,
            'carrier.primary'                                     => true,
            'carrier.subscriptionId'                              => null,
            'carrier.type'                                        => 'main',
            'collectionContact'                                   => null,
            'created'                                             => '2022-07-12 17:28:27',
            'createdBy'                                           => 82444,
            'customsDeclaration'                                  => null,
            'delayed'                                             => false,
            'delivered'                                           => false,
            'deliveryOptions.carrier'                             => CarrierOptions::CARRIER_POSTNL_NAME,
            'deliveryOptions.date'                                => null,
            'deliveryOptions.deliveryType'                        => '4',
            'deliveryOptions.labelAmount'                         => 1,
            'deliveryOptions.packageType'                         => '1',
            'deliveryOptions.pickupLocation.boxNumber'            => null,
            'deliveryOptions.pickupLocation.cc'                   => 'NL',
            'deliveryOptions.pickupLocation.city'                 => 'BOSKOOP',
            'deliveryOptions.pickupLocation.fullStreet'           => null,
            'deliveryOptions.pickupLocation.locationCode'         => '216107',
            'deliveryOptions.pickupLocation.locationName'         => 'Wolswijk thodn Intertoys Boskoop',
            'deliveryOptions.pickupLocation.number'               => '7',
            'deliveryOptions.pickupLocation.numberSuffix'         => null,
            'deliveryOptions.pickupLocation.postalCode'           => '2771GS',
            'deliveryOptions.pickupLocation.region'               => null,
            'deliveryOptions.pickupLocation.retailNetworkId'      => 'PNPNL-01',
            'deliveryOptions.pickupLocation.state'                => null,
            'deliveryOptions.pickupLocation.street'               => 'Kerkstraat',
            'deliveryOptions.pickupLocation.streetAdditionalInfo' => null,
            'deliveryOptions.shipmentOptions.ageCheck'            => false,
            'deliveryOptions.shipmentOptions.insurance'           => 0,
            'deliveryOptions.shipmentOptions.labelDescription'    => '',
            'deliveryOptions.shipmentOptions.largeFormat'         => false,
            'deliveryOptions.shipmentOptions.onlyRecipient'       => false,
            'deliveryOptions.shipmentOptions.return'              => false,
            'deliveryOptions.shipmentOptions.sameDayDelivery'     => false,
            'deliveryOptions.shipmentOptions.signature'           => true,
            'dropOffPoint'                                        => null,
            'externalIdentifier'                                  => '3SMYPA056396924',
            'id'                                                  => 136464938,
            'isReturn'                                            => false,
            'linkConsumerPortal'                                  => null,
            'modified'                                            => '2022-07-12 17:28:28',
            'modifiedBy'                                          => 82444,
            'multiCollo'                                          => false,
            'multiColloMainShipmentId'                            => null,
            'orderId'                                             => null,
            'partnerTrackTraces'                                  => [],
            'physicalProperties.height'                           => null,
            'physicalProperties.length'                           => null,
            'physicalProperties.weight'                           => 1000,
            'physicalProperties.width'                            => null,
            'recipient.boxNumber'                                 => null,
            'recipient.cc'                                        => 'NL',
            'recipient.city'                                      => 'Boskoop',
            'recipient.company'                                   => null,
            'recipient.email'                                     => 'mooieplanten@kweker.nl',
            'recipient.fullStreet'                                => null,
            'recipient.number'                                    => '25',
            'recipient.numberSuffix'                              => 'a',
            'recipient.person'                                    => 'Piet Boomkweker',
            'recipient.phone'                                     => '0613124565',
            'recipient.postalCode'                                => '2771AX',
            'recipient.region'                                    => null,
            'recipient.state'                                     => null,
            'recipient.street'                                    => 'Azalealaan',
            'recipient.streetAdditionalInfo'                      => null,
            'referenceIdentifier'                                 => '',
            'sender.boxNumber'                                    => null,
            'sender.cc'                                           => 'NL',
            'sender.city'                                         => 'Hoofddorp',
            'sender.company'                                      => 'MyParcel',
            'sender.email'                                        => 'mrparcel@myparcel.nl',
            'sender.fullStreet'                                   => null,
            'sender.number'                                       => '31',
            'sender.numberSuffix'                                 => null,
            'sender.person'                                       => 'Mister Parcel',
            'sender.phone'                                        => '0606607834',
            'sender.postalCode'                                   => '2132JE',
            'sender.region'                                       => null,
            'sender.state'                                        => null,
            'sender.street'                                       => 'Antareslaan',
            'sender.streetAdditionalInfo'                         => null,
            'shopId'                                              => 93683,
            'status'                                              => 2,
            'updated'                                             => null,
        ],
    ],
    'shipment with contract'       => [
        'response' => ExampleGetShipmentsFromContractResponse::class,
        'output'   => [
            'apiKey'                                           => null,
            'barcode'                                          => '3SMYPA123456789',
            'carrier.human'                                    => null,
            'carrier.id'                                       => 4,
            'carrier.isDefault'                                => null,
            'carrier.label'                                    => null,
            'carrier.name'                                     => 'dpd',
            'carrier.optional'                                 => null,
            'carrier.primary'                                  => false,
            'carrier.subscriptionId'                           => 10932621,
            'carrier.type'                                     => 'custom',
            'collectionContact'                                => null,
            'created'                                          => '2022-07-25 15:16:31',
            'createdBy'                                        => 145,
            'customsDeclaration'                               => null,
            'delayed'                                          => false,
            'delivered'                                        => false,
            'deliveryOptions.carrier'                          => 'dpd',
            'deliveryOptions.date'                             => null,
            'deliveryOptions.deliveryType'                     => '2',
            'deliveryOptions.labelAmount'                      => 1,
            'deliveryOptions.packageType'                      => '1',
            'deliveryOptions.pickupLocation'                   => null,
            'deliveryOptions.shipmentOptions.ageCheck'         => null,
            'deliveryOptions.shipmentOptions.insurance'        => 0,
            'deliveryOptions.shipmentOptions.labelDescription' => null,
            'deliveryOptions.shipmentOptions.largeFormat'      => null,
            'deliveryOptions.shipmentOptions.onlyRecipient'    => null,
            'deliveryOptions.shipmentOptions.return'           => null,
            'deliveryOptions.shipmentOptions.sameDayDelivery'  => null,
            'deliveryOptions.shipmentOptions.signature'        => null,
            'dropOffPoint'                                     => null,
            'externalIdentifier'                               => '3SMYPA060119130',
            'id'                                               => 23001,
            'isReturn'                                         => false,
            'linkConsumerPortal'                               => 'https://demo.myparcel.me/track-trace/demo',
            'modified'                                         => '2022-07-25 15:16:31',
            'modifiedBy'                                       => 145,
            'multiCollo'                                       => true,
            'multiColloMainShipmentId'                         => '23001',
            'orderId'                                          => null,
            'partnerTrackTraces'                               => [],
            'physicalProperties'                               => null,
            'recipient.boxNumber'                              => null,
            'recipient.cc'                                     => 'NL',
            'recipient.city'                                   => 'Hoofddorp',
            'recipient.company'                                => null,
            'recipient.email'                                  => null,
            'recipient.fullStreet'                             => null,
            'recipient.number'                                 => '31',
            'recipient.numberSuffix'                           => null,
            'recipient.person'                                 => 'Jaap Krekel',
            'recipient.phone'                                  => null,
            'recipient.postalCode'                             => '2132JE',
            'recipient.region'                                 => null,
            'recipient.state'                                  => null,
            'recipient.street'                                 => 'Antareslaan',
            'recipient.streetAdditionalInfo'                   => null,
            'referenceIdentifier'                              => 'my-multicollo-set',
            'sender.boxNumber'                                 => null,
            'sender.cc'                                        => 'NL',
            'sender.city'                                      => 'Hoofddorp',
            'sender.company'                                   => 'MyParcel',
            'sender.email'                                     => 'spam@myparcel.nl',
            'sender.fullStreet'                                => null,
            'sender.number'                                    => '31',
            'sender.numberSuffix'                              => null,
            'sender.person'                                    => 'Bye Felicia',
            'sender.phone'                                     => '0612345678',
            'sender.postalCode'                                => '2132 JE',
            'sender.region'                                    => null,
            'sender.state'                                     => null,
            'sender.street'                                    => 'Antareslaan',
            'sender.streetAdditionalInfo'                      => null,
            'shopId'                                           => 67890,
            'status'                                           => 2,
            'updated'                                          => null,
        ],
    ],
]);
