default:
  autoload:
    '': 'tests/Features'

  suites:
    default:
      paths:
        - 'tests/Integration/Features'
      contexts:
        - MyParcelNL\Pdk\Tests\Integration\Context\FeatureContext
        - MyParcelNL\Pdk\Tests\Integration\Context\RequestContext
        - MyParcelNL\Pdk\Tests\Integration\Context\SettingsContext
