name: '♻️ Analyse'

on:
  workflow_call:

jobs:
  analyse:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v5
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.credentials.outputs.token }}

      - name: 'Handle PHPStan cache'
        uses: actions/cache@v4
        id: phpstan-cache
        with:
          path: './.cache/phpstan'
          key: phpstan-cache-${{ vars.PHP_VERSION }}-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-${{ hashFiles('**/*.php') }}
          restore-keys: |
            phpstan-cache-${{ vars.PHP_VERSION }}-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-
            phpstan-cache-${{ hashFiles('phpstan.neon.dist', 'composer.json') }}-
            phpstan-cache-

      - uses: ./.github/actions/setup
        if: steps.phpstan-cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          php-version: ${{ vars.PHP_VERSION }}

      - name: 'Run PHPStan analysis'
        if: steps.phpstan-cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          docker compose run php php -dmemory_limit=-1 vendor/bin/phpstan analyse --no-progress --no-interaction
