name: '🔸 Upload coverage'

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage

      - uses: codecov/codecov-action@v3
        continue-on-error: true

      - uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
