name: '♻️ Quality'

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Whether to run in dry-run mode'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          token: ${{ steps.credentials.outputs.token }}

      - name: 'Handle Rector cache'
        uses: actions/cache@v3
        id: rector-cache
        with:
          path: './.cache/rector'
          key: rector-cache-${{ hashFiles('composer.json') }}-${{ hashFiles('**/*.php') }}
          restore-keys: |
            rector-cache-${{ hashFiles('composer.json') }}-
            rector-cache-

      - uses: ./.github/actions/setup
        if: steps.rector-cache.outputs.cache-hit != 'true'

      - name: 'Run Rector'
        if: steps.rector-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          docker compose run php \
            vendor/bin/rector process \
              --no-progress-bar \
              --ansi \
              ${{ github.event.inputs.dry-run == 'true' && '--dry-run' || '' }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event.inputs.dry-run != 'true' && steps.rector-cache.outputs.cache-hit != 'true'
        with:
          commit_message: 'style(rector): apply changes'
          commit_options: '--no-verify --signoff'
          commit_user_name: ${{ steps.credentials.outputs.git-name }}
          commit_user_email: ${{ steps.credentials.outputs.git-email }}
          commit_author: '${{ steps.credentials.outputs.git-name }} <${{ steps.credentials.outputs.git-email }}>'
