name: '♻️ Quality'

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Whether to run in dry-run mode'
        required: false
        type: boolean
        default: false

jobs:
  quality:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v4
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v5
        with:
          token: ${{ steps.credentials.outputs.token }}

      - name: 'Handle Rector cache'
        uses: actions/cache@v4
        id: rector-cache
        with:
          path: './.cache/rector'
          key: rector-cache-${{ vars.PHP_VERSION }}-${{ hashFiles('composer.json') }}-${{ hashFiles('rector.php', 'src/**/*.php', 'config/**/*.php', 'tests/**/*.php') }}
          restore-keys: |
            rector-cache-${{ vars.PHP_VERSION }}-${{ hashFiles('composer.json') }}-
            rector-cache-${{ hashFiles('composer.json') }}-
            rector-cache-

      - uses: ./.github/actions/setup
        if: steps.rector-cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          php-version: ${{ vars.PHP_VERSION }}

      - name: 'Run quality checks in dry-run mode'
        if: steps.rector-cache.outputs.cache-hit != 'true' && github.event.inputs.dry-run == 'true'
        shell: bash
        #language=bash
        run: |
          docker compose run php composer quality

      - name: 'Run quality checks and apply changes'
        if: steps.rector-cache.outputs.cache-hit != 'true' && github.event.inputs.dry-run != 'true'
        shell: bash
        #language=bash
        run: |
          docker compose run php composer quality:fix

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        if: steps.rector-cache.outputs.cache-hit != 'true' && github.event.inputs.dry-run != 'true'
#        with:
#          commit_message: 'style(rector): apply changes'
#          commit_options: '--no-verify --signoff'
#          commit_user_name: ${{ steps.credentials.outputs.git-name }}
#          commit_user_email: ${{ steps.credentials.outputs.git-email }}
#          commit_author: '${{ steps.credentials.outputs.git-name }} <${{ steps.credentials.outputs.git-email }}>'
