name: '♻️ Quality'

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Whether to run in dry-run mode'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/quality
        with:
          dry-run: ${{ github.event.inputs.dry-run }}
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
