name: '♻️ Run integration tests'

on:
  workflow_call:

jobs:
  test-integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: 'Run integration tests'
        shell: bash
        run: |
          docker compose run php vendor/bin/behat --colors --no-interaction
