name: '🔸 Run tests 🧪'

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  test:
    name: 'Run pest tests'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ steps.credentials.outputs.token }}

      - uses: actions/cache@v3
        id: cache-coverage
        with:
          path: ./clover.xml
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/composer.lock', './Dockerfile', './src/**', './tests/**') }}

      - name: 'Run tests'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: |
          docker run \
            --volume $PWD:/app \
            ghcr.io/myparcelnl/php-xd:7.4 \
            sh -c 'composer install --dev --no-progress --no-suggest --no-scripts --no-plugins && ./vendor/bin/pest'

      - name: 'Get coverage file from container'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: docker cp $(docker ps -alq):/app/clover.xml .

      - uses: codecov/codecov-action@v3

      - uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
