name: '🔸 Run tests 🧪'

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  test:
    name: 'Run pest tests'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: myparcelnl/actions/setup-git-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ steps.credentials.outputs.token }}

      - uses: actions/cache@v3
        id: cache-coverage
        with:
          path: ./clover.xml
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/composer.lock', './Dockerfile', './src/**', './tests/**') }}

      - uses: ./.github/actions/build-docker-image-reg
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        id: docker
        with:
          image: ${{ github.repository_owner }}/php-pdk
          target: test
          registry-user: ${{ github.actor }}
          registry-password: ${{ steps.credentials.outputs.token }}

      - name: 'Run tests'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: docker run ${{ steps.docker.outputs.tagged-image }}

      - name: 'Get coverage file from container'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: docker cp $(docker ps -alq):/app/clover.xml .

      - uses: codecov/codecov-action@v3

      - uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
