name: '♻️ Run unit tests'

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version'
        required: false
        type: string
        default: '7.4'

jobs:
  test-unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: 'Handle coverage cache'
        uses: actions/cache@v5
        id: coverage-cache
        with:
          path: ./clover.xml
          key: coverage-clover-${{ inputs.php-version }}-${{ hashFiles('**/composer.lock', './src/**', './config/**', './tests/**', './.github/workflows/--test-unit.yml') }}

      - uses: ./.github/actions/setup
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          php-version: ${{ inputs.php-version }}

      - name: 'Run unit tests'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        shell: bash
        env:
          PHP_VERSION: ${{ inputs.php-version }}
        #language=bash
        run: |
          docker compose run php \
            php -dmemory_limit=512M -dpcov.enabled=1 -dauto_prepend_file=tests/bootstrap.php \
            vendor/bin/pest \
              --colors=always \
              --coverage-clover=clover.xml \
              --no-interaction

          # Strip the /app/ prefix from the coverage paths before uploading.
          sed -i 's/\/app\///g' clover.xml

      - uses: codecov/codecov-action@v6
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
