name: 'Run merge group checks ⚙️'

on:
  merge_group:

jobs:
  test-unit:
    uses: ./.github/workflows/--test-unit.yml
    secrets: inherit

  test-integration:
    uses: ./.github/workflows/--test-integration.yml
    secrets: inherit

  analyse:
    uses: ./.github/workflows/--analyse.yml
    secrets: inherit

  quality:
    uses: ./.github/workflows/--quality.yml
    secrets: inherit
    with:
      dry-run: true
