name: 'Run merge group checks ⚙️'

on:
  merge_group:

jobs:
  setup:
    uses: ./.github/workflows/--setup.yml
    secrets: inherit

  test:
    needs: setup
    uses: ./.github/workflows/--test.yml
    secrets: inherit

  quality:
    needs: setup
    uses: ./.github/workflows/--quality.yml
    secrets: inherit
    with:
      dry-run: true
