name: 'Run merge group checks ⚙️'

on:
  merge_group:

jobs:
  test:
    uses: ./.github/workflows/--test.yml
    secrets: inherit

  quality:
    uses: ./.github/workflows/--quality.yml
    secrets: inherit
    with:
      dry-run: true
