name: 'Run pull request checks ⚙️'

on:
  pull_request:
    branches:
      - main
      - alpha
      - beta
      - rc

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # Run setup initially to save cache and time on subsequent jobs
  setup:
    uses: ./.github/workflows/--setup.yml
    secrets: inherit

  test-unit:
    needs: setup
    uses: ./.github/workflows/--test-unit.yml
    secrets: inherit

  test-integration:
    needs: setup
    uses: ./.github/workflows/--test-integration.yml
    secrets: inherit

  analyse:
    needs: setup
    uses: ./.github/workflows/--analyse.yml
    secrets: inherit

  quality:
    needs: setup
    uses: ./.github/workflows/--quality.yml
    secrets: inherit
