name: 'Run pull request checks ⚙️'

on:
  pull_request:
    branches:
      - main
      - alpha
      - beta
      - rc

concurrency:
  group: ${{github.workflow}}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-unit:
    uses: ./.github/workflows/--test-unit.yml
    secrets: inherit

  test-integration:
    uses: ./.github/workflows/--test-integration.yml
    secrets: inherit

  analyse:
    uses: ./.github/workflows/--analyse.yml
    secrets: inherit

  quality:
    uses: ./.github/workflows/--quality.yml
    secrets: inherit
