name: 'Pull request'

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/--test.yml
    secrets: inherit

  coverage:
    needs: test
    uses: ./.github/workflows/--coverage.yml
    secrets: inherit
