name: 'On push ⚙️'

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - rc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    uses: ./.github/workflows/--test-unit.yml
    secrets: inherit

  test-integration:
    uses: ./.github/workflows/--test-integration.yml
    secrets: inherit

  analyse:
    uses: ./.github/workflows/--analyse.yml
    secrets: inherit

  quality:
    uses: ./.github/workflows/--quality.yml
    with:
      dry-run: true
    secrets: inherit

  rebase-prs:
    needs:
      - test-unit
      - test-integration
      - analyse
      - quality
    uses: ./.github/workflows/--rebase-prs.yml
    secrets: inherit
