name: 'On push ⚙️'

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - rc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/--setup.yml
    secrets: inherit

  test:
    needs: setup
    uses: ./.github/workflows/--test.yml
    secrets: inherit

  quality:
    needs: setup
    uses: ./.github/workflows/--quality.yml
    with:
      dry-run: true
    secrets: inherit

  rebase-prs:
    needs:
      - test
      - quality
    if: always()
    uses: ./.github/workflows/--rebase-prs.yml
    secrets: inherit
