name: 'Run tests 🧪'
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        if: github.actor != 'dependabot[bot]'
        with:
          persist-credentials: false

      - uses: myparcelnl/actions/build-docker-image-reg@v2
        if: github.actor != 'dependabot[bot]'
        id: docker
        with:
          image: myparcelnl/php-pdk
          target: test
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run tests'
        if: github.actor != 'dependabot[bot]'
        run: docker run ${{ steps.docker.outputs.tagged-image }}

      - name: 'Get coverage file from container'
        if: github.actor != 'dependabot[bot]'
        run: docker cp $(docker ps -alq):/app/coverage.xml .

      - uses: codecov/codecov-action@v3
        if: github.actor != 'dependabot[bot]'

      - uses: codacy/codacy-coverage-reporter-action@v1
        if: github.actor != 'dependabot[bot]'
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
