name: 'Run tests 🧪'
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/cache@v3
        id: cache-coverage
        with:
          path: ./clover.xml
          key: ${{ runner.os }}-coverage-${{ hashFiles('**/composer.lock', './Dockerfile', './src/**', './tests/**') }}

      - uses: myparcelnl/actions/build-docker-image-reg@v2
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        id: docker
        with:
          image: myparcelnl/php-pdk
          target: test
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run tests'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: docker run ${{ steps.docker.outputs.tagged-image }}

      - name: 'Get coverage file from container'
        if: steps.cache-coverage.outputs.cache-hit != 'true'
        run: docker cp $(docker ps -alq):/app/clover.xml .

      - uses: codecov/codecov-action@v3

      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
