name: 'Run tests 🧪'
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: myparcelnl/actions/build-docker-image-reg@v2
        id: docker
        with:
          image: myparcelnl/php-pdk
          target: test
          registry-user: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Run tests'
        run: docker run ${{ steps.docker.outputs.tagged-image }}

      - name: 'Get coverage file from container'
        run: docker cp $(docker ps -alq):/app/coverage.xml .

      - name: Update code coverage
        uses: codecov/codecov-action@v3
